name: "NPM Publisher"
description: "A GitHub action for automating publishing NPM packages"
inputs:
  registry:
    description: "NPM registry. Usually 'registry.npmjs.org'"
    required: false
    default: "registry.npmjs.org"
  access-token:
    description: "NPM access token for authenticating to npm"
    required: true
branding:
  icon: "shield"
  color: "blue"
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.registry }}
    - ${{ inputs.access-token }}
